/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsOfUseIndexRouteImport } from './routes/terms-of-use/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as PrivacyPolicyIndexRouteImport } from './routes/privacy-policy/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ImprintIndexRouteImport } from './routes/imprint/index'
import { Route as ForgotIndexRouteImport } from './routes/forgot/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as TcgIndexRouteImport } from './routes/$tcg/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as MeSettingsIndexRouteImport } from './routes/me/settings/index'
import { Route as MeSavedSearchesIndexRouteImport } from './routes/me/saved-searches/index'
import { Route as MeHistoryIndexRouteImport } from './routes/me/history/index'
import { Route as AtChar123userChar125ListsIndexRouteImport } from './routes/@{$user}/lists/index'
import { Route as TcgSetsIndexRouteImport } from './routes/$tcg/sets/index'
import { Route as TcgKitchenIndexRouteImport } from './routes/$tcg/kitchen/index'
import { Route as TcgCardsIndexRouteImport } from './routes/$tcg/cards/index'
import { Route as AuthEmailTokenRouteImport } from './routes/auth/email/$token'
import { Route as AuthConfirmTokenRouteImport } from './routes/auth/confirm/$token'
import { Route as AtChar123userChar125ListsListIdRouteImport } from './routes/@{$user}/lists/$listId'
import { Route as TcgCardsPrintIdRouteImport } from './routes/$tcg/cards/$printId'
import { Route as TcgSetsSetCodeIndexRouteImport } from './routes/$tcg/sets/$setCode/index'
import { Route as TcgSetsSetCodeCollectorNumberChar123AnyChar125RouteImport } from './routes/$tcg/sets/$setCode/$collectorNumber/{-$any}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseIndexRoute = TermsOfUseIndexRouteImport.update({
  id: '/terms-of-use/',
  path: '/terms-of-use/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyIndexRoute = PrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintIndexRoute = ImprintIndexRouteImport.update({
  id: '/imprint/',
  path: '/imprint/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotIndexRoute = ForgotIndexRouteImport.update({
  id: '/forgot/',
  path: '/forgot/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgIndexRoute = TcgIndexRouteImport.update({
  id: '/$tcg/',
  path: '/$tcg/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeSettingsIndexRoute = MeSettingsIndexRouteImport.update({
  id: '/me/settings/',
  path: '/me/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeSavedSearchesIndexRoute = MeSavedSearchesIndexRouteImport.update({
  id: '/me/saved-searches/',
  path: '/me/saved-searches/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeHistoryIndexRoute = MeHistoryIndexRouteImport.update({
  id: '/me/history/',
  path: '/me/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123userChar125ListsIndexRoute =
  AtChar123userChar125ListsIndexRouteImport.update({
    id: '/@{$user}/lists/',
    path: '/@{$user}/lists/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TcgSetsIndexRoute = TcgSetsIndexRouteImport.update({
  id: '/$tcg/sets/',
  path: '/$tcg/sets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgKitchenIndexRoute = TcgKitchenIndexRouteImport.update({
  id: '/$tcg/kitchen/',
  path: '/$tcg/kitchen/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgCardsIndexRoute = TcgCardsIndexRouteImport.update({
  id: '/$tcg/cards/',
  path: '/$tcg/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailTokenRoute = AuthEmailTokenRouteImport.update({
  id: '/auth/email/$token',
  path: '/auth/email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmTokenRoute = AuthConfirmTokenRouteImport.update({
  id: '/auth/confirm/$token',
  path: '/auth/confirm/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123userChar125ListsListIdRoute =
  AtChar123userChar125ListsListIdRouteImport.update({
    id: '/@{$user}/lists/$listId',
    path: '/@{$user}/lists/$listId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TcgCardsPrintIdRoute = TcgCardsPrintIdRouteImport.update({
  id: '/$tcg/cards/$printId',
  path: '/$tcg/cards/$printId',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgSetsSetCodeIndexRoute = TcgSetsSetCodeIndexRouteImport.update({
  id: '/$tcg/sets/$setCode/',
  path: '/$tcg/sets/$setCode/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgSetsSetCodeCollectorNumberChar123AnyChar125Route =
  TcgSetsSetCodeCollectorNumberChar123AnyChar125RouteImport.update({
    id: '/$tcg/sets/$setCode/$collectorNumber/{-$any}',
    path: '/$tcg/sets/$setCode/$collectorNumber/{-$any}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/$tcg/': typeof TcgIndexRoute
  '/about/': typeof AboutIndexRoute
  '/forgot/': typeof ForgotIndexRoute
  '/imprint/': typeof ImprintIndexRoute
  '/login/': typeof LoginIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/terms-of-use/': typeof TermsOfUseIndexRoute
  '/$tcg/cards/$printId': typeof TcgCardsPrintIdRoute
  '/@{$user}/lists/$listId': typeof AtChar123userChar125ListsListIdRoute
  '/auth/confirm/$token': typeof AuthConfirmTokenRoute
  '/auth/email/$token': typeof AuthEmailTokenRoute
  '/$tcg/cards/': typeof TcgCardsIndexRoute
  '/$tcg/kitchen/': typeof TcgKitchenIndexRoute
  '/$tcg/sets/': typeof TcgSetsIndexRoute
  '/@{$user}/lists/': typeof AtChar123userChar125ListsIndexRoute
  '/me/history/': typeof MeHistoryIndexRoute
  '/me/saved-searches/': typeof MeSavedSearchesIndexRoute
  '/me/settings/': typeof MeSettingsIndexRoute
  '/$tcg/sets/$setCode/': typeof TcgSetsSetCodeIndexRoute
  '/$tcg/sets/$setCode/$collectorNumber/{-$any}': typeof TcgSetsSetCodeCollectorNumberChar123AnyChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/$tcg': typeof TcgIndexRoute
  '/about': typeof AboutIndexRoute
  '/forgot': typeof ForgotIndexRoute
  '/imprint': typeof ImprintIndexRoute
  '/login': typeof LoginIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/privacy-policy': typeof PrivacyPolicyIndexRoute
  '/register': typeof RegisterIndexRoute
  '/terms-of-use': typeof TermsOfUseIndexRoute
  '/$tcg/cards/$printId': typeof TcgCardsPrintIdRoute
  '/@{$user}/lists/$listId': typeof AtChar123userChar125ListsListIdRoute
  '/auth/confirm/$token': typeof AuthConfirmTokenRoute
  '/auth/email/$token': typeof AuthEmailTokenRoute
  '/$tcg/cards': typeof TcgCardsIndexRoute
  '/$tcg/kitchen': typeof TcgKitchenIndexRoute
  '/$tcg/sets': typeof TcgSetsIndexRoute
  '/@{$user}/lists': typeof AtChar123userChar125ListsIndexRoute
  '/me/history': typeof MeHistoryIndexRoute
  '/me/saved-searches': typeof MeSavedSearchesIndexRoute
  '/me/settings': typeof MeSettingsIndexRoute
  '/$tcg/sets/$setCode': typeof TcgSetsSetCodeIndexRoute
  '/$tcg/sets/$setCode/$collectorNumber/{-$any}': typeof TcgSetsSetCodeCollectorNumberChar123AnyChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/$tcg/': typeof TcgIndexRoute
  '/about/': typeof AboutIndexRoute
  '/forgot/': typeof ForgotIndexRoute
  '/imprint/': typeof ImprintIndexRoute
  '/login/': typeof LoginIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/terms-of-use/': typeof TermsOfUseIndexRoute
  '/$tcg/cards/$printId': typeof TcgCardsPrintIdRoute
  '/@{$user}/lists/$listId': typeof AtChar123userChar125ListsListIdRoute
  '/auth/confirm/$token': typeof AuthConfirmTokenRoute
  '/auth/email/$token': typeof AuthEmailTokenRoute
  '/$tcg/cards/': typeof TcgCardsIndexRoute
  '/$tcg/kitchen/': typeof TcgKitchenIndexRoute
  '/$tcg/sets/': typeof TcgSetsIndexRoute
  '/@{$user}/lists/': typeof AtChar123userChar125ListsIndexRoute
  '/me/history/': typeof MeHistoryIndexRoute
  '/me/saved-searches/': typeof MeSavedSearchesIndexRoute
  '/me/settings/': typeof MeSettingsIndexRoute
  '/$tcg/sets/$setCode/': typeof TcgSetsSetCodeIndexRoute
  '/$tcg/sets/$setCode/$collectorNumber/{-$any}': typeof TcgSetsSetCodeCollectorNumberChar123AnyChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts/$postId'
    | '/$tcg/'
    | '/about/'
    | '/forgot/'
    | '/imprint/'
    | '/login/'
    | '/playground/'
    | '/privacy-policy/'
    | '/register/'
    | '/terms-of-use/'
    | '/$tcg/cards/$printId'
    | '/@{$user}/lists/$listId'
    | '/auth/confirm/$token'
    | '/auth/email/$token'
    | '/$tcg/cards/'
    | '/$tcg/kitchen/'
    | '/$tcg/sets/'
    | '/@{$user}/lists/'
    | '/me/history/'
    | '/me/saved-searches/'
    | '/me/settings/'
    | '/$tcg/sets/$setCode/'
    | '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts/$postId'
    | '/$tcg'
    | '/about'
    | '/forgot'
    | '/imprint'
    | '/login'
    | '/playground'
    | '/privacy-policy'
    | '/register'
    | '/terms-of-use'
    | '/$tcg/cards/$printId'
    | '/@{$user}/lists/$listId'
    | '/auth/confirm/$token'
    | '/auth/email/$token'
    | '/$tcg/cards'
    | '/$tcg/kitchen'
    | '/$tcg/sets'
    | '/@{$user}/lists'
    | '/me/history'
    | '/me/saved-searches'
    | '/me/settings'
    | '/$tcg/sets/$setCode'
    | '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
  id:
    | '__root__'
    | '/'
    | '/posts/$postId'
    | '/$tcg/'
    | '/about/'
    | '/forgot/'
    | '/imprint/'
    | '/login/'
    | '/playground/'
    | '/privacy-policy/'
    | '/register/'
    | '/terms-of-use/'
    | '/$tcg/cards/$printId'
    | '/@{$user}/lists/$listId'
    | '/auth/confirm/$token'
    | '/auth/email/$token'
    | '/$tcg/cards/'
    | '/$tcg/kitchen/'
    | '/$tcg/sets/'
    | '/@{$user}/lists/'
    | '/me/history/'
    | '/me/saved-searches/'
    | '/me/settings/'
    | '/$tcg/sets/$setCode/'
    | '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  TcgIndexRoute: typeof TcgIndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ForgotIndexRoute: typeof ForgotIndexRoute
  ImprintIndexRoute: typeof ImprintIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  PrivacyPolicyIndexRoute: typeof PrivacyPolicyIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  TermsOfUseIndexRoute: typeof TermsOfUseIndexRoute
  TcgCardsPrintIdRoute: typeof TcgCardsPrintIdRoute
  AtChar123userChar125ListsListIdRoute: typeof AtChar123userChar125ListsListIdRoute
  AuthConfirmTokenRoute: typeof AuthConfirmTokenRoute
  AuthEmailTokenRoute: typeof AuthEmailTokenRoute
  TcgCardsIndexRoute: typeof TcgCardsIndexRoute
  TcgKitchenIndexRoute: typeof TcgKitchenIndexRoute
  TcgSetsIndexRoute: typeof TcgSetsIndexRoute
  AtChar123userChar125ListsIndexRoute: typeof AtChar123userChar125ListsIndexRoute
  MeHistoryIndexRoute: typeof MeHistoryIndexRoute
  MeSavedSearchesIndexRoute: typeof MeSavedSearchesIndexRoute
  MeSettingsIndexRoute: typeof MeSettingsIndexRoute
  TcgSetsSetCodeIndexRoute: typeof TcgSetsSetCodeIndexRoute
  TcgSetsSetCodeCollectorNumberChar123AnyChar125Route: typeof TcgSetsSetCodeCollectorNumberChar123AnyChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use/': {
      id: '/terms-of-use/'
      path: '/terms-of-use'
      fullPath: '/terms-of-use/'
      preLoaderRoute: typeof TermsOfUseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy/': {
      id: '/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof PrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint/': {
      id: '/imprint/'
      path: '/imprint'
      fullPath: '/imprint/'
      preLoaderRoute: typeof ImprintIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot/': {
      id: '/forgot/'
      path: '/forgot'
      fullPath: '/forgot/'
      preLoaderRoute: typeof ForgotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/': {
      id: '/$tcg/'
      path: '/$tcg'
      fullPath: '/$tcg/'
      preLoaderRoute: typeof TcgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/settings/': {
      id: '/me/settings/'
      path: '/me/settings'
      fullPath: '/me/settings/'
      preLoaderRoute: typeof MeSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/saved-searches/': {
      id: '/me/saved-searches/'
      path: '/me/saved-searches'
      fullPath: '/me/saved-searches/'
      preLoaderRoute: typeof MeSavedSearchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/history/': {
      id: '/me/history/'
      path: '/me/history'
      fullPath: '/me/history/'
      preLoaderRoute: typeof MeHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$user}/lists/': {
      id: '/@{$user}/lists/'
      path: '/@{$user}/lists'
      fullPath: '/@{$user}/lists/'
      preLoaderRoute: typeof AtChar123userChar125ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/sets/': {
      id: '/$tcg/sets/'
      path: '/$tcg/sets'
      fullPath: '/$tcg/sets/'
      preLoaderRoute: typeof TcgSetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/kitchen/': {
      id: '/$tcg/kitchen/'
      path: '/$tcg/kitchen'
      fullPath: '/$tcg/kitchen/'
      preLoaderRoute: typeof TcgKitchenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/cards/': {
      id: '/$tcg/cards/'
      path: '/$tcg/cards'
      fullPath: '/$tcg/cards/'
      preLoaderRoute: typeof TcgCardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email/$token': {
      id: '/auth/email/$token'
      path: '/auth/email/$token'
      fullPath: '/auth/email/$token'
      preLoaderRoute: typeof AuthEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm/$token': {
      id: '/auth/confirm/$token'
      path: '/auth/confirm/$token'
      fullPath: '/auth/confirm/$token'
      preLoaderRoute: typeof AuthConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$user}/lists/$listId': {
      id: '/@{$user}/lists/$listId'
      path: '/@{$user}/lists/$listId'
      fullPath: '/@{$user}/lists/$listId'
      preLoaderRoute: typeof AtChar123userChar125ListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/cards/$printId': {
      id: '/$tcg/cards/$printId'
      path: '/$tcg/cards/$printId'
      fullPath: '/$tcg/cards/$printId'
      preLoaderRoute: typeof TcgCardsPrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/sets/$setCode/': {
      id: '/$tcg/sets/$setCode/'
      path: '/$tcg/sets/$setCode'
      fullPath: '/$tcg/sets/$setCode/'
      preLoaderRoute: typeof TcgSetsSetCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/sets/$setCode/$collectorNumber/{-$any}': {
      id: '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
      path: '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
      fullPath: '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
      preLoaderRoute: typeof TcgSetsSetCodeCollectorNumberChar123AnyChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  TcgIndexRoute: TcgIndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  ForgotIndexRoute: ForgotIndexRoute,
  ImprintIndexRoute: ImprintIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  PrivacyPolicyIndexRoute: PrivacyPolicyIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  TermsOfUseIndexRoute: TermsOfUseIndexRoute,
  TcgCardsPrintIdRoute: TcgCardsPrintIdRoute,
  AtChar123userChar125ListsListIdRoute: AtChar123userChar125ListsListIdRoute,
  AuthConfirmTokenRoute: AuthConfirmTokenRoute,
  AuthEmailTokenRoute: AuthEmailTokenRoute,
  TcgCardsIndexRoute: TcgCardsIndexRoute,
  TcgKitchenIndexRoute: TcgKitchenIndexRoute,
  TcgSetsIndexRoute: TcgSetsIndexRoute,
  AtChar123userChar125ListsIndexRoute: AtChar123userChar125ListsIndexRoute,
  MeHistoryIndexRoute: MeHistoryIndexRoute,
  MeSavedSearchesIndexRoute: MeSavedSearchesIndexRoute,
  MeSettingsIndexRoute: MeSettingsIndexRoute,
  TcgSetsSetCodeIndexRoute: TcgSetsSetCodeIndexRoute,
  TcgSetsSetCodeCollectorNumberChar123AnyChar125Route:
    TcgSetsSetCodeCollectorNumberChar123AnyChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
