/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as TcgIndexRouteImport } from './routes/$tcg/index'
import { Route as TcgCardsIndexRouteImport } from './routes/$tcg/cards/index'
import { Route as TcgAdvancedIndexRouteImport } from './routes/$tcg/advanced/index'
import { Route as TcgSetsSetCodeIndexRouteImport } from './routes/$tcg/sets/$setCode/index'
import { Route as TcgSetsSetCodeCollectorNumberChar123AnyChar125RouteImport } from './routes/$tcg/sets/$setCode/$collectorNumber/{-$any}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgIndexRoute = TcgIndexRouteImport.update({
  id: '/$tcg/',
  path: '/$tcg/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgCardsIndexRoute = TcgCardsIndexRouteImport.update({
  id: '/$tcg/cards/',
  path: '/$tcg/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgAdvancedIndexRoute = TcgAdvancedIndexRouteImport.update({
  id: '/$tcg/advanced/',
  path: '/$tcg/advanced/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgSetsSetCodeIndexRoute = TcgSetsSetCodeIndexRouteImport.update({
  id: '/$tcg/sets/$setCode/',
  path: '/$tcg/sets/$setCode/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcgSetsSetCodeCollectorNumberChar123AnyChar125Route =
  TcgSetsSetCodeCollectorNumberChar123AnyChar125RouteImport.update({
    id: '/$tcg/sets/$setCode/$collectorNumber/{-$any}',
    path: '/$tcg/sets/$setCode/$collectorNumber/{-$any}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tcg': typeof TcgIndexRoute
  '/login': typeof LoginIndexRoute
  '/$tcg/advanced': typeof TcgAdvancedIndexRoute
  '/$tcg/cards': typeof TcgCardsIndexRoute
  '/$tcg/sets/$setCode': typeof TcgSetsSetCodeIndexRoute
  '/$tcg/sets/$setCode/$collectorNumber/{-$any}': typeof TcgSetsSetCodeCollectorNumberChar123AnyChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$tcg': typeof TcgIndexRoute
  '/login': typeof LoginIndexRoute
  '/$tcg/advanced': typeof TcgAdvancedIndexRoute
  '/$tcg/cards': typeof TcgCardsIndexRoute
  '/$tcg/sets/$setCode': typeof TcgSetsSetCodeIndexRoute
  '/$tcg/sets/$setCode/$collectorNumber/{-$any}': typeof TcgSetsSetCodeCollectorNumberChar123AnyChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tcg/': typeof TcgIndexRoute
  '/login/': typeof LoginIndexRoute
  '/$tcg/advanced/': typeof TcgAdvancedIndexRoute
  '/$tcg/cards/': typeof TcgCardsIndexRoute
  '/$tcg/sets/$setCode/': typeof TcgSetsSetCodeIndexRoute
  '/$tcg/sets/$setCode/$collectorNumber/{-$any}': typeof TcgSetsSetCodeCollectorNumberChar123AnyChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tcg'
    | '/login'
    | '/$tcg/advanced'
    | '/$tcg/cards'
    | '/$tcg/sets/$setCode'
    | '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$tcg'
    | '/login'
    | '/$tcg/advanced'
    | '/$tcg/cards'
    | '/$tcg/sets/$setCode'
    | '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
  id:
    | '__root__'
    | '/'
    | '/$tcg/'
    | '/login/'
    | '/$tcg/advanced/'
    | '/$tcg/cards/'
    | '/$tcg/sets/$setCode/'
    | '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TcgIndexRoute: typeof TcgIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  TcgAdvancedIndexRoute: typeof TcgAdvancedIndexRoute
  TcgCardsIndexRoute: typeof TcgCardsIndexRoute
  TcgSetsSetCodeIndexRoute: typeof TcgSetsSetCodeIndexRoute
  TcgSetsSetCodeCollectorNumberChar123AnyChar125Route: typeof TcgSetsSetCodeCollectorNumberChar123AnyChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/': {
      id: '/$tcg/'
      path: '/$tcg'
      fullPath: '/$tcg'
      preLoaderRoute: typeof TcgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/cards/': {
      id: '/$tcg/cards/'
      path: '/$tcg/cards'
      fullPath: '/$tcg/cards'
      preLoaderRoute: typeof TcgCardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/advanced/': {
      id: '/$tcg/advanced/'
      path: '/$tcg/advanced'
      fullPath: '/$tcg/advanced'
      preLoaderRoute: typeof TcgAdvancedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/sets/$setCode/': {
      id: '/$tcg/sets/$setCode/'
      path: '/$tcg/sets/$setCode'
      fullPath: '/$tcg/sets/$setCode'
      preLoaderRoute: typeof TcgSetsSetCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tcg/sets/$setCode/$collectorNumber/{-$any}': {
      id: '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
      path: '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
      fullPath: '/$tcg/sets/$setCode/$collectorNumber/{-$any}'
      preLoaderRoute: typeof TcgSetsSetCodeCollectorNumberChar123AnyChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TcgIndexRoute: TcgIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  TcgAdvancedIndexRoute: TcgAdvancedIndexRoute,
  TcgCardsIndexRoute: TcgCardsIndexRoute,
  TcgSetsSetCodeIndexRoute: TcgSetsSetCodeIndexRoute,
  TcgSetsSetCodeCollectorNumberChar123AnyChar125Route:
    TcgSetsSetCodeCollectorNumberChar123AnyChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
