export const typesAndClassifications = {
  statusCode: 200,
  data: {
    total: 43,
    matches: 40,
    values: [
      { value: 'action', type: 'type' },
      { value: 'alien', type: 'classification' },
      { value: 'ally', type: 'classification' },
      { value: 'broom', type: 'classification' },
      { value: 'captain', type: 'classification' },
      { value: 'character', type: 'type' },
      { value: 'colossus', type: 'classification' },
      { value: 'deity', type: 'classification' },
      { value: 'detective', type: 'classification' },
      { value: 'dragon', type: 'classification' },
      { value: 'dreamborn', type: 'classification' },
      { value: 'entangled', type: 'classification' },
      { value: 'fairy', type: 'classification' },
      { value: 'floodborn', type: 'classification' },
      { value: 'hero', type: 'classification' },
      { value: 'hyena', type: 'classification' },
      { value: 'illusion', type: 'classification' },
      { value: 'inventor', type: 'classification' },
      { value: 'item', type: 'type' },
      { value: 'king', type: 'classification' },
      { value: 'knight', type: 'classification' },
      { value: 'location', type: 'type' },
      { value: 'madrigal', type: 'classification' },
      { value: 'mentor', type: 'classification' },
      { value: 'musketeer', type: 'classification' },
      { value: 'obstacle', type: 'classification' },
      { value: 'pirate', type: 'classification' },
      { value: 'prince', type: 'classification' },
      { value: 'princess', type: 'classification' },
      { value: 'puppy', type: 'classification' },
      { value: 'queen', type: 'classification' },
      { value: 'racer', type: 'classification' },
      { value: 'robot', type: 'classification' },
      { value: 'seven dwarfs', type: 'classification', aliases: ['sevendwarfs'] },
      { value: 'song', type: 'classification' },
      { value: 'sorcerer', type: 'classification' },
      { value: 'storyborn', type: 'classification' },
      { value: 'tigger', type: 'classification' },
      { value: 'titan', type: 'classification' },
      { value: 'villain', type: 'classification' },
    ],
  },
};

export const inks = {
  statusCode: 200,
  data: {
    total: 7,
    matches: 7,
    values: [
      { value: 'amber', type: 'dlc_ink_type' },
      { value: 'amethyst', type: 'dlc_ink_type' },
      { value: 'emerald', type: 'dlc_ink_type' },
      { value: 'none', type: 'dlc_ink_type' },
      { value: 'ruby', type: 'dlc_ink_type' },
      { value: 'sapphire', type: 'dlc_ink_type' },
      { value: 'steel', type: 'dlc_ink_type' },
    ],
  },
};

export const rarities = {
  statusCode: 200,
  data: {
    total: 7,
    matches: 7,
    values: [
      { value: 'common', type: 'rarity' },
      { value: 'enchanted', type: 'rarity' },
      { value: 'legendary', type: 'rarity' },
      { value: 'promo', type: 'rarity', aliases: ['special'] },
      { value: 'rare', type: 'rarity' },
      { value: 'super_rare', type: 'rarity', aliases: ['super', 'superrare'] },
      { value: 'uncommon', type: 'rarity' },
    ],
  },
};

export const setNames = {
  statusCode: 200,
  data: {
    total: 14,
    matches: 14,
    values: [
      { value: 'Archazia’s Island', type: 'name' },
      { value: 'Azurite Sea', type: 'name' },
      { value: 'C1', type: 'name' },
      { value: 'D23', type: 'name' },
      { value: 'Deep Trouble', type: 'name' },
      { value: 'Into the Inklands', type: 'name' },
      { value: 'Palace Heist', type: 'name' },
      { value: 'Promo', type: 'name' },
      { value: 'Promo 2', type: 'name' },
      { value: 'Reign of Jafar', type: 'name' },
      { value: 'Rise of the Floodborn', type: 'name' },
      { value: 'Shimmering Skies', type: 'name' },
      { value: 'The First Chapter', type: 'name' },
      { value: "Ursula's Return", type: 'name' },
    ],
  },
};

export const setCodes = {
  statusCode: 200,
  data: {
    total: 19,
    matches: 19,
    values: [
      { value: '1', type: 'code' },
      { value: '2', type: 'code' },
      { value: '3', type: 'code' },
      { value: '4', type: 'code' },
      { value: '5', type: 'code' },
      { value: '6', type: 'code' },
      { value: '7', type: 'code' },
      { value: '8', type: 'code' },
      { value: 'C1', type: 'code' },
      { value: 'D23', type: 'code' },
      { value: 'P1', type: 'code' },
      { value: 'P2', type: 'code' },
      { value: 'Q1', type: 'code' },
      { value: 'Q2', type: 'code' },
      { value: 'ink', type: 'set_code', resolvesTo: '3' },
      { value: 'promo', type: 'set_code', resolvesTo: 'P1' },
      { value: 'rof', type: 'set_code', resolvesTo: '2' },
      { value: 'tfc', type: 'set_code', resolvesTo: '1' },
      { value: 'urs', type: 'set_code', resolvesTo: '4' },
    ],
  },
};

export const franchises = {
  statusCode: 200,
  data: {
    total: 78,
    matches: 78,
    values: [
      { value: '101 Dalmatians', type: 'name' },
      { value: '101-dalmatians', type: 'slug' },
      { value: 'Aladdin', type: 'name' },
      { value: 'Alice in Wonderland', type: 'name' },
      { value: 'Atlantis', type: 'name' },
      { value: 'Beauty & the Beast', type: 'name' },
      { value: 'Big Hero 6', type: 'name' },
      { value: 'Brother Bear', type: 'name' },
      { value: "Chip 'n' Dale Rescue Rangers", type: 'name' },
      { value: 'Cinderella', type: 'name' },
      { value: 'Disney Lorcana', type: 'name' },
      { value: 'Duck Tales', type: 'name' },
      { value: 'Encanto', type: 'name' },
      { value: 'Fantasia', type: 'name' },
      { value: 'Frozen', type: 'name' },
      { value: 'Hercules', type: 'name' },
      { value: 'Lilo and Stitch', type: 'name' },
      { value: 'Mickey Mouse and Friends', type: 'name' },
      { value: 'Moana', type: 'name' },
      { value: 'Mulan', type: 'name' },
      { value: 'Peter Pan', type: 'name' },
      { value: 'Pinocchio', type: 'name' },
      { value: 'Raya and the Last Dragon', type: 'name' },
      { value: 'Robin Hood', type: 'name' },
      { value: 'Sleeping Beauty', type: 'name' },
      { value: 'Snow White and the Seven Dwarfs', type: 'name' },
      { value: 'TaleSpin', type: 'name' },
      { value: 'Tangled', type: 'name' },
      { value: "The Emperor's New Groove", type: 'name' },
      { value: 'The Great Mouse Detective', type: 'name' },
      { value: 'The Jungle Book', type: 'name' },
      { value: 'The Lion King', type: 'name' },
      { value: 'The Little Mermaid', type: 'name' },
      { value: 'The Princess and the Frog', type: 'name' },
      { value: 'The Rescuers', type: 'name' },
      { value: 'The Sword in the Stone', type: 'name' },
      { value: 'Treasure Planet', type: 'name' },
      { value: 'Winnie the Pooh', type: 'name' },
      { value: 'Wreck it Ralph', type: 'name' },
      { value: 'Zootopia', type: 'name' },
      { value: 'aladdin', type: 'slug' },
      { value: 'alice-in-wonderland', type: 'slug' },
      { value: 'atlantis', type: 'slug' },
      { value: 'beauty-and-the-beast', type: 'slug' },
      { value: 'big-hero-6', type: 'slug' },
      { value: 'brother-bear', type: 'slug' },
      { value: 'chip-n-dale-rescue-rangers', type: 'slug' },
      { value: 'cinderella', type: 'slug' },
      { value: 'disney-lorcana', type: 'slug' },
      { value: 'duck-tales', type: 'slug' },
      { value: 'encanto', type: 'slug' },
      { value: 'fantasia', type: 'slug' },
      { value: 'frozen', type: 'slug' },
      { value: 'great-mouse-detective', type: 'slug' },
      { value: 'hercules', type: 'slug' },
      { value: 'jungle-book', type: 'slug' },
      { value: 'lilo-and-stitch', type: 'slug' },
      { value: 'micky-mouse-and-friends', type: 'slug' },
      { value: 'moana', type: 'slug' },
      { value: 'mulan', type: 'slug' },
      { value: 'peter-pan', type: 'slug' },
      { value: 'pinocchio', type: 'slug' },
      { value: 'raya-and-the-last-dragon', type: 'slug' },
      { value: 'robin-hood', type: 'slug' },
      { value: 'sleeping-beauty', type: 'slug' },
      { value: 'snow-white-and-the-seven-dwarfs', type: 'slug' },
      { value: 'talespin', type: 'slug' },
      { value: 'tangled', type: 'slug' },
      { value: 'the-emperors-new-groove', type: 'slug' },
      { value: 'the-lion-king', type: 'slug' },
      { value: 'the-little-mermaid', type: 'slug' },
      { value: 'the-princess-and-the-frog', type: 'slug' },
      { value: 'the-rescuers', type: 'slug' },
      { value: 'the-sword-in-the-stone', type: 'slug' },
      { value: 'treasure-planet', type: 'slug' },
      { value: 'winnie-the-pooh', type: 'slug' },
      { value: 'wreck-it-ralph', type: 'slug' },
      { value: 'zootopia', type: 'slug' },
    ],
  },
};
