/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Users
         * @description Search users by specific parameters
         */
        get: {
            parameters: {
                query?: {
                    /** @description The page number to retrieve */
                    page?: number;
                    /** @description The number of entries per page */
                    pageSize?: number;
                    /** @description Hi Benedikt */
                    searchBy?: "username" | "displayname" | "email";
                    /** @description Hi Benedikt */
                    searchValue?: string;
                    /** @description Hi Benedikt */
                    sortBy?: "username" | "displayname" | "createdAt" | "lastActiveAt";
                    /** @description Hi Benedikt */
                    sortOrder?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-SimplePage-DataAuthUser"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id or username of the user. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get User
         * @description Get a user by id or username.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or username of the user. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-DataAuthUser"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}/impersonate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id or username of the user. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Impersonate User
         * @description Impersonate a user by id or username. Returns a token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or username of the user. */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Request Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImpersonateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-GeneratedApiToken"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id or username of the user. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get Tokens
         * @description Returns all user tokens, including admin ones.
         */
        get: {
            parameters: {
                query: {
                    /** @description The page number to retrieve */
                    page: number;
                    /** @description The number of entries per page */
                    pageSize: number;
                    /** @description If set, also returns ratelimits for the user and specific tokens. */
                    withRatelimits?: string;
                    /** @description If set will not filter out expired tokens. */
                    showExpired?: string;
                    /** @description Filters the type of token */
                    type?: "USER" | "ADMIN";
                    /** @description Sort by specific field */
                    sortBy?: "name" | "created_at";
                    /** @description Sorting order if sortBy is set */
                    sortOrder?: "asc" | "desc";
                };
                header?: never;
                path: {
                    /** @description The id or username of the user. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-UserTokensResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create Token
         * @description Creates a new token for that user
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or username of the user. */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Request Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateApiTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-GeneratedApiToken"];
                    };
                };
            };
        };
        /**
         * Delete Tokens
         * @description Deletes given tokens for that user
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or username of the user. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id or username of the user. */
                id: string;
                /** @description Id of the token of the user */
                tokenId: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Update Token
         * @description Updates given token for that user
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or username of the user. */
                    id: string;
                    /** @description Id of the token of the user */
                    tokenId: string;
                };
                cookie?: never;
            };
            /** @description Request Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateApiTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-ApiToken"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Roles
         * @description Get paginated roles
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-List-UserRole"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create Role
         * @description Creates a new user role based on given parameters
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-UserRole"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        /**
         * Get Role
         * @description Get role by id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-UserRole"];
                    };
                };
            };
        };
        /**
         * Update Role
         * @description Updates role by id
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roleId: string;
                };
                cookie?: never;
            };
            /** @description Request Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleApiResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete Role
         * @description Deletes specific role by id
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/datareports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for data issue reports
         * @description Searches for reports on data issues based on given parameters.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Targeted TCG of the report. */
                    game?: "mtg" | "ygo" | "pcg" | "dlc" | "one" | "fab";
                    /** @description Id of the reported subject. */
                    subjectId?: string;
                    /** @description Id of the assigned person handling the report. */
                    assignedTo?: string;
                    /** @description Status of the report. */
                    status?: "reported" | "ongoing" | "resolved" | "blocked";
                    /** @description Status of the report. */
                    excludeStatus?: "reported" | "ongoing" | "resolved" | "blocked";
                    /** @description Field to sort the returned reports by. */
                    sortBy?: "reported_at";
                    /** @description The order of sorting, either ascending or descending. */
                    sortOrder?: "asc" | "desc";
                    /** @description The id of the page to return. Defaults to `0`. */
                    page?: number;
                    /** @description The amount of items to return per page. Defaults to `10`. */
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-SimplePage-DataIssueReport"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Report a data issue
         * @description Reports that some data (card, set) has an issue.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReportDataIssueRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-ReportDataIssueResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/datareports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the data issue report */
                reportId: string;
            };
            cookie?: never;
        };
        /**
         * Get a data issue reports
         * @description Returns the report with given id, if found.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id of the data issue report */
                    reportId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-DataIssueReport"];
                    };
                };
            };
        };
        /**
         * Update a data issue report
         * @description Updates the report with given id, if found.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id of the data issue report */
                    reportId: string;
                };
                cookie?: never;
            };
            /** @description Request Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDataIssueReportRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-UpdateDataIssueResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for release calendar entries
         * @description Searches for release calendar entries based on given parameters.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Targeted TCG of the calendar entry. */
                    game?: "mtg" | "ygo" | "pcg" | "dlc" | "one" | "fab";
                    /** @description Target year of the calendar entry. */
                    year?: number;
                    /** @description Field to sort the returned reports by. */
                    sortBy?: "lgs_release" | "retail_release";
                    /** @description The order of sorting, either ascending or descending. */
                    sortOrder?: "asc" | "desc";
                    /** @description The id of the page to return. Defaults to `0`. */
                    page?: number;
                    /** @description The amount of items to return per page. Defaults to `10`. */
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-SimplePage-ReleaseCalendarEntry"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Creates a release calendar entry
         * @description Creates a release calendar entry with given body
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateReleaseCalendarRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-CreateReleaseCalendarResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calendar/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the release calendar entry */
                entryId: string;
            };
            cookie?: never;
        };
        /**
         * Get a release calendar entry
         * @description Returns the calendar entry with given id, if found.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id of the release calendar entry */
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-ReleaseCalendarEntry"];
                    };
                };
            };
        };
        /**
         * Update a release calendar entry
         * @description Updates the entry with given id, if found.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id of the release calendar entry */
                    entryId: string;
                };
                cookie?: never;
            };
            /** @description Request Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateReleaseCalendarRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-UpdateReleaseCalendarResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a release calendar entry
         * @description Deletes an entry with given id, if found.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id of the release calendar entry */
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dumplings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for dumplings
         * @description Searches for dumplings based on given parameters.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Source of the dumplings to filter by. */
                    source?: string;
                    /** @description Endpoint of the dumplings to filter by. */
                    endpoint?: string;
                    /** @description Type of the dumplings to filter by. */
                    type?: "full" | "changes" | "snapshot" | "multi";
                    /** @description Storage device where the dumpling was stored on. */
                    storageDevice?: "s3_dev" | "s3_cloudflare";
                    /** @description Major version of the dumplings to filter by. */
                    versionMinor?: number;
                    /** @description Minor version of the dumplings to filter by. */
                    versionMajor?: number;
                    /** @description If `true` will exclude all deleted dumplings. */
                    excludeDeleted?: string;
                    /** @description Field to sort the returned dumplings by. */
                    sortBy?: "created_at" | "version";
                    /** @description The order of sorting, either ascending or descending. */
                    sortOrder?: "asc" | "desc";
                    /** @description The id of the page to return. Defaults to `0`. */
                    page?: number;
                    /** @description The amount of items to return per page. Defaults to `10`. */
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-SimplePage-Dumpling"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dumplings/{dumplingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the dumpling as uuid or source:version */
                dumplingId: string;
            };
            cookie?: never;
        };
        /**
         * Get a dumpling
         * @description Returns the dumpling with given id, if found.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id of the dumpling as uuid or source:version */
                    dumplingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-Dumpling"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dumplings/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources and endpoints.
         * @description Get all sources and endpoints for all dumplings in database.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-Map-String-List-String"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Rotom activities
         * @description Searches for Rotom activities based on given parameters.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Target subject of the activity. */
                    subject?: string;
                    /** @description Target type of the activity. */
                    type?: string;
                    /** @description Target result of the activity. */
                    result?: "success" | "success_with_warnings" | "error";
                    /** @description Field to sort the returned activites by. */
                    sortBy?: "subject" | "type" | "result" | "started_at" | "finished_at" | "sent_to_discord_at";
                    /** @description The order of sorting, either ascending or descending. */
                    sortOrder?: "asc" | "desc";
                    /** @description The id of the page to return. Defaults to `0`. */
                    page?: number;
                    /** @description The amount of items to return per page. Defaults to `10`. */
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-SimplePage-RotomActivity"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/{activityId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the activity */
                activityId: string;
            };
            cookie?: never;
        };
        /**
         * Get Rotom activity
         * @description Returns Rotom activity with given id, if found.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id of the activity */
                    activityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataApiResponse-RotomActivity"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JsonArray: unknown[];
        JsonObject: Record<string, never>;
        JsonPrimitive: string | boolean | number;
        JsonElement: Record<string, never>;
        /** Format: date */
        LocalDate: string;
        /** Format: time */
        LocalTime: string;
        /** Format: date-time */
        LocalDateTime: string;
        /** Format: date-time */
        OffsetDateTime: string;
        SimpleApiResponse: {
            /** Format: int32 */
            statusCode: number;
        };
        /** @enum {string} */
        UserLanguage: "en" | "de";
        /** @enum {string} */
        MtgLanguage: "en" | "de" | "fr" | "it" | "es" | "pt" | "el" | "ar" | "zhs" | "zht" | "he" | "jp" | "ko" | "la" | "ph" | "ru" | "sa" | "qy";
        /** @enum {string} */
        PcgLanguage: "en" | "fr" | "es" | "pt" | "it" | "de" | "nl" | "ru" | "pl" | "jp" | "ko" | "zht" | "zhs" | "cmn" | "yue" | "th" | "id";
        /** @enum {string} */
        YgoLanguage: "en" | "en_north_america" | "en_europe" | "en_australia" | "en_asia" | "fr" | "fr_canada" | "de" | "it" | "pt" | "es" | "jp" | "jp_asia" | "ko" | "zht" | "zhs";
        /** @enum {string} */
        Visibility: "public" | "private";
        /** @enum {string} */
        UserState: "unverified" | "verified";
        UserRole: {
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            limits: components["schemas"]["JsonObject"];
            name: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PreferredLanguageSettings: {
            dlc?: string;
            global?: components["schemas"]["UserLanguage"];
            mtg?: components["schemas"]["MtgLanguage"];
            pcg?: components["schemas"]["PcgLanguage"];
            ygo?: components["schemas"]["YgoLanguage"];
        };
        PrivacySettings: {
            activityVisibility?: components["schemas"]["Visibility"];
            collectionVisibility?: components["schemas"]["Visibility"];
            profileVisibility?: components["schemas"]["Visibility"];
        };
        UserSettings: {
            preferredLanguages?: components["schemas"]["PreferredLanguageSettings"];
            privacy?: components["schemas"]["PrivacySettings"];
        };
        DataAuthUser: {
            admin: boolean;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            displayName: string;
            email: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            lastActivityAt: string;
            roles: components["schemas"]["UserRole"][];
            settings: components["schemas"]["UserSettings"];
            state?: components["schemas"]["UserState"];
            username: string;
        };
        "SimplePage-DataAuthUser": {
            /** Format: int32 */
            currentPage: number;
            hasNextPage: boolean;
            items: components["schemas"]["DataAuthUser"][];
            /** Format: int32 */
            lastPage: number;
            /** Format: int32 */
            nextPage: number;
        };
        ApiError: {
            key: string;
            message?: string | null;
            reasons?: string[] | null;
        };
        ErrorApiResponse: {
            error: components["schemas"]["ApiError"];
            /** Format: int32 */
            statusCode: number;
        };
        "DataApiResponse-SimplePage-DataAuthUser": {
            data: components["schemas"]["SimplePage-DataAuthUser"];
            /** Format: int32 */
            statusCode: number;
        };
        "DataApiResponse-DataAuthUser": {
            data: components["schemas"]["DataAuthUser"];
            /** Format: int32 */
            statusCode: number;
        };
        ImpersonateUserRequest: {
            /** Format: date-time */
            expiresAt: string;
            name?: string | null;
            ratelimit?: number | null;
        };
        /** @enum {string} */
        ApiTokenType: "USER" | "ADMIN";
        ApiToken: {
            /** Format: date-time */
            createdAt: string;
            expiresAt?: string | null;
            /** Format: uuid */
            id: string;
            lastUsedAt?: string | null;
            name: string;
            rateLimit?: number | null;
            token: components["schemas"]["ByteArray"];
            type: components["schemas"]["ApiTokenType"];
            userId?: string | null;
        };
        ByteArray: Record<string, never>;
        GeneratedApiToken: {
            apiToken: components["schemas"]["ApiToken"];
            secret: string;
        };
        "DataApiResponse-GeneratedApiToken": {
            data: components["schemas"]["GeneratedApiToken"];
            /** Format: int32 */
            statusCode: number;
        };
        "SimplePage-ApiToken": {
            /** Format: int32 */
            currentPage: number;
            hasNextPage: boolean;
            items: components["schemas"]["ApiToken"][];
            /** Format: int32 */
            lastPage: number;
            /** Format: int32 */
            nextPage: number;
        };
        RateLimitUsage: {
            duration: components["schemas"]["Duration"];
            /** Format: int64 */
            max: number;
            /** Format: int64 */
            usage: number;
        };
        Duration: {
            /** Format: int64 */
            rawValue: number;
        };
        UserTokensResponseRateLimits: {
            byToken: {
                [key: string]: components["schemas"]["RateLimitUsage"];
            };
            global: components["schemas"]["RateLimitUsage"];
        };
        UserTokensResponse: {
            page: components["schemas"]["SimplePage-ApiToken"];
            ratelimits?: components["schemas"]["UserTokensResponseRateLimits"] | null;
        };
        "DataApiResponse-UserTokensResponse": {
            data: components["schemas"]["UserTokensResponse"];
            /** Format: int32 */
            statusCode: number;
        };
        CreateApiTokenRequest: {
            expiresAt?: string | null;
            name?: string | null;
            rateLimit?: number | null;
            type: components["schemas"]["ApiTokenType"];
        };
        DeleteApiTokenRequest: {
            tokenIds: string[];
        };
        UpdateApiTokenRequest: {
            expiresAt?: string | null;
            name?: string | null;
            rateLimit?: number | null;
            resetExpiresAt?: boolean | null;
            resetRateLimit?: boolean | null;
        };
        "DataApiResponse-ApiToken": {
            data: components["schemas"]["ApiToken"];
            /** Format: int32 */
            statusCode: number;
        };
        CreateUserRoleRequest: {
            limits: {
                [key: string]: number;
            };
            name: string;
        };
        "DataApiResponse-UserRole": {
            data: components["schemas"]["UserRole"];
            /** Format: int32 */
            statusCode: number;
        };
        "DataApiResponse-List-UserRole": {
            data: components["schemas"]["UserRole"][];
            /** Format: int32 */
            statusCode: number;
        };
        UpdateUserRoleRequest: {
            limits?: null | {
                [key: string]: number;
            };
            name?: string | null;
        };
        /** @enum {string} */
        GameType: "mtg" | "ygo" | "pcg" | "dlc" | "one" | "fab";
        /** @enum {string} */
        DataIssueReportReporterType: "unknown" | "user";
        /** @enum {string} */
        DataIssueReportSeverity: "unknown" | "minor" | "medium" | "major";
        /** @enum {string} */
        DataIssueReportStatus: "reported" | "ongoing" | "resolved" | "blocked";
        /** @enum {string} */
        DataIssueReportSubjectType: "card" | "set" | "block";
        /** @enum {string} */
        DataIssueReportTarget: "image" | "text" | "field" | "price" | "relations" | "other";
        DataIssueReport: {
            assignedTo?: string | null;
            /** Format: date-time */
            createdAt: string;
            game: components["schemas"]["GameType"];
            /** Format: uuid */
            id: string;
            internalNote?: string | null;
            note?: string | null;
            /** Format: date-time */
            reportedAt: string;
            reporterId?: string | null;
            reporterName?: string | null;
            reporterType: components["schemas"]["DataIssueReportReporterType"];
            resolvedAt?: string | null;
            severity: components["schemas"]["DataIssueReportSeverity"];
            status: components["schemas"]["DataIssueReportStatus"];
            subjectId?: string | null;
            subjectType: components["schemas"]["DataIssueReportSubjectType"];
            target: components["schemas"]["DataIssueReportTarget"];
            url?: string | null;
        };
        "SimplePage-DataIssueReport": {
            /** Format: int32 */
            currentPage: number;
            hasNextPage: boolean;
            items: components["schemas"]["DataIssueReport"][];
            /** Format: int32 */
            lastPage: number;
            /** Format: int32 */
            nextPage: number;
        };
        "DataApiResponse-SimplePage-DataIssueReport": {
            data: components["schemas"]["SimplePage-DataIssueReport"];
            /** Format: int32 */
            statusCode: number;
        };
        ReportDataIssueRequest: {
            gameType: components["schemas"]["GameType"];
            note?: string | null;
            reporterId?: string | null;
            reporterName?: string | null;
            reporterType?: components["schemas"]["DataIssueReportReporterType"] | null;
            severity?: components["schemas"]["DataIssueReportSeverity"] | null;
            subjectId?: string | null;
            subjectType: components["schemas"]["DataIssueReportSubjectType"];
            target?: components["schemas"]["DataIssueReportTarget"] | null;
            url?: string | null;
        };
        ReportDataIssueResponse: {
            report: components["schemas"]["DataIssueReport"];
        };
        "DataApiResponse-ReportDataIssueResponse": {
            data: components["schemas"]["ReportDataIssueResponse"];
            /** Format: int32 */
            statusCode: number;
        };
        "DataApiResponse-DataIssueReport": {
            data: components["schemas"]["DataIssueReport"];
            /** Format: int32 */
            statusCode: number;
        };
        UpdateDataIssueReportRequest: {
            assignedTo?: string | null;
            gameType?: components["schemas"]["GameType"] | null;
            internalNote?: string | null;
            note?: string | null;
            reporterId?: string | null;
            reporterName?: string | null;
            reporterType?: components["schemas"]["DataIssueReportReporterType"] | null;
            severity?: components["schemas"]["DataIssueReportSeverity"] | null;
            status?: components["schemas"]["DataIssueReportStatus"] | null;
            subjectId?: string | null;
            subjectType?: components["schemas"]["DataIssueReportSubjectType"] | null;
            target?: components["schemas"]["DataIssueReportTarget"] | null;
            url?: string | null;
        };
        UpdateDataIssueResponse: {
            report: components["schemas"]["DataIssueReport"];
        };
        "DataApiResponse-UpdateDataIssueResponse": {
            data: components["schemas"]["UpdateDataIssueResponse"];
            /** Format: int32 */
            statusCode: number;
        };
        /** @enum {string} */
        ReleaseCalendarEntryType: "main_expansion" | "special_expansion" | "deck_and_other";
        CreateReleaseCalendarRequest: {
            gameType: components["schemas"]["GameType"];
            lgsRelease?: string | null;
            name: string;
            note?: string | null;
            retailRelease?: string | null;
            sourceUrl?: string | null;
            type: components["schemas"]["ReleaseCalendarEntryType"];
        };
        ReleaseCalendarEntry: {
            game: components["schemas"]["GameType"];
            /** Format: uuid */
            id: string;
            lgsRelease?: string | null;
            name: string;
            note?: string | null;
            retailRelease?: string | null;
            sourceUrl?: string | null;
            type: components["schemas"]["ReleaseCalendarEntryType"];
        };
        CreateReleaseCalendarResponse: {
            entry: components["schemas"]["ReleaseCalendarEntry"];
        };
        "DataApiResponse-CreateReleaseCalendarResponse": {
            data: components["schemas"]["CreateReleaseCalendarResponse"];
            /** Format: int32 */
            statusCode: number;
        };
        "SimplePage-ReleaseCalendarEntry": {
            /** Format: int32 */
            currentPage: number;
            hasNextPage: boolean;
            items: components["schemas"]["ReleaseCalendarEntry"][];
            /** Format: int32 */
            lastPage: number;
            /** Format: int32 */
            nextPage: number;
        };
        "DataApiResponse-SimplePage-ReleaseCalendarEntry": {
            data: components["schemas"]["SimplePage-ReleaseCalendarEntry"];
            /** Format: int32 */
            statusCode: number;
        };
        "DataApiResponse-ReleaseCalendarEntry": {
            data: components["schemas"]["ReleaseCalendarEntry"];
            /** Format: int32 */
            statusCode: number;
        };
        UpdateReleaseCalendarRequest: {
            lgsRelease?: string | null;
            name?: string | null;
            note?: string | null;
            retailRelease?: string | null;
            sourceUrl?: string | null;
            type?: components["schemas"]["ReleaseCalendarEntryType"] | null;
        };
        UpdateReleaseCalendarResponse: {
            entry: components["schemas"]["ReleaseCalendarEntry"];
        };
        "DataApiResponse-UpdateReleaseCalendarResponse": {
            data: components["schemas"]["UpdateReleaseCalendarResponse"];
            /** Format: int32 */
            statusCode: number;
        };
        /** @enum {string} */
        SearchQuerySource: "CHEF" | "CUSTOM";
        /** @enum {string} */
        SearchQueryTarget: "CARD" | "PRINT" | "SET" | "BLOCK";
        RelatedSearchQuery: {
            gameType: components["schemas"]["GameType"];
            /** Format: uuid */
            id: string;
            name: string;
            query: string;
            /** Format: int32 */
            sortValue: number;
            source: components["schemas"]["SearchQuerySource"];
            /** Format: uuid */
            targetId: string;
            targetType: components["schemas"]["SearchQueryTarget"];
        };
        RelatedSearchQueryApiRelatedQueryPatchRequest: {
            gameType: components["schemas"]["GameType"];
            name: string;
            query: string;
            /** Format: int32 */
            sortValue: number;
            /** Format: uuid */
            targetId: string;
            targetType: components["schemas"]["SearchQueryTarget"];
        };
        "DataApiResponse-RelatedSearchQuery": {
            data: components["schemas"]["RelatedSearchQuery"];
            /** Format: int32 */
            statusCode: number;
        };
        /** @enum {string} */
        StorageDevice: "s3_dev" | "s3_cloudflare";
        /** @enum {string} */
        DumplingType: "full" | "changes" | "snapshot" | "multi";
        Dumpling: {
            /** Format: date-time */
            createdAt: string;
            deletedAt?: string | null;
            endpoint: string;
            /** Format: uuid */
            id: string;
            metadata?: Record<string, never> | null;
            path: string;
            source: string;
            storageDevice: components["schemas"]["StorageDevice"];
            type: components["schemas"]["DumplingType"];
            /** Format: int32 */
            versionMajor: number;
            /** Format: int32 */
            versionMinor: number;
            writeIndex?: string | null;
        };
        "SimplePage-Dumpling": {
            /** Format: int32 */
            currentPage: number;
            hasNextPage: boolean;
            items: components["schemas"]["Dumpling"][];
            /** Format: int32 */
            lastPage: number;
            /** Format: int32 */
            nextPage: number;
        };
        "DataApiResponse-SimplePage-Dumpling": {
            data: components["schemas"]["SimplePage-Dumpling"];
            /** Format: int32 */
            statusCode: number;
        };
        "DataApiResponse-Dumpling": {
            data: components["schemas"]["Dumpling"];
            /** Format: int32 */
            statusCode: number;
        };
        "DataApiResponse-Map-String-List-String": {
            data: {
                [key: string]: string[];
            };
            /** Format: int32 */
            statusCode: number;
        };
        /** @enum {string} */
        ActivityResult: "success" | "success_with_warnings" | "error";
        RotomActivity: {
            activityData: components["schemas"]["JsonObject"];
            finishedAt?: string | null;
            /** Format: uuid */
            id: string;
            message?: string | null;
            result: components["schemas"]["ActivityResult"];
            sentToDiscordAt?: string | null;
            /** Format: date-time */
            startedAt: string;
            subject: string;
            type: string;
        };
        "SimplePage-RotomActivity": {
            /** Format: int32 */
            currentPage: number;
            hasNextPage: boolean;
            items: components["schemas"]["RotomActivity"][];
            /** Format: int32 */
            lastPage: number;
            /** Format: int32 */
            nextPage: number;
        };
        "DataApiResponse-SimplePage-RotomActivity": {
            data: components["schemas"]["SimplePage-RotomActivity"];
            /** Format: int32 */
            statusCode: number;
        };
        "DataApiResponse-RotomActivity": {
            data: components["schemas"]["RotomActivity"];
            /** Format: int32 */
            statusCode: number;
        };
        QueryStatisticsApiSearchQueryExecutionStatistics: {
            /** Format: int32 */
            count: number;
            lastExecutedAt?: string | null;
            /** Format: double */
            latencyMax: number;
            /** Format: double */
            latencyMedian: number;
            /** Format: double */
            latencyMin: number;
        };
        QueryStatisticsApiSearchQueryEntry: {
            game: components["schemas"]["GameType"];
            /** Format: uuid */
            id: string;
            query: string;
            statistics: components["schemas"]["QueryStatisticsApiSearchQueryExecutionStatistics"];
        };
        "Page-QueryStatisticsApiSearchQueryEntry": {
            /** Format: int32 */
            currentPage: number;
            hasNextPage: boolean;
            items: components["schemas"]["QueryStatisticsApiSearchQueryEntry"][];
            /** Format: int32 */
            pageCount: number;
            /** Format: int32 */
            totalItemCount: number;
        };
        QueryStatisticsApiLatencies: {
            max: number[];
            median: number[];
            min: number[];
        };
        QueryStatisticsApiSearchQueryAggregate: {
            intervals: string[];
            latencies: components["schemas"]["QueryStatisticsApiLatencies"];
            queriesByGame: {
                [key: string]: (null | number)[];
            };
        };
        "DataApiResponse-QueryStatisticsApiSearchQueryAggregate": {
            data: components["schemas"]["QueryStatisticsApiSearchQueryAggregate"];
            /** Format: int32 */
            statusCode: number;
        };
        SearchQuery: {
            expressions: string[];
            filters: string[];
            game: components["schemas"]["GameType"];
            hash: string;
            /** Format: uuid */
            id: string;
            query: string;
        };
        "DataApiResponse-SearchQuery": {
            data: components["schemas"]["SearchQuery"];
            /** Format: int32 */
            statusCode: number;
        };
        /** @enum {string} */
        AuthType: "anonymous" | "user" | "token";
        /** @enum {string} */
        Order: "asc" | "desc";
        SearchQueryStatistics: {
            /** Format: int32 */
            attempt: number;
            authIdentifier?: string | null;
            authType: components["schemas"]["AuthType"];
            cached: boolean;
            /** Format: date-time */
            createdAt: string;
            distinctMode: string;
            /** Format: int64 */
            executionTime: number;
            flags: string[];
            /** Format: uuid */
            id: string;
            language: string;
            origin?: string | null;
            /** Format: uuid */
            queryId: string;
            rawQuery: string;
            /** Format: int32 */
            results: number;
            searchMode: string;
            sortDirection: components["schemas"]["Order"];
            sortMode: string;
            strippedQuery: string;
            userAgent?: string | null;
        };
        "Page-SearchQueryStatistics": {
            /** Format: int32 */
            currentPage: number;
            hasNextPage: boolean;
            items: components["schemas"]["SearchQueryStatistics"][];
            /** Format: int32 */
            pageCount: number;
            /** Format: int32 */
            totalItemCount: number;
        };
        /** @enum {string} */
        ImageSubject: "card" | "set" | "user_avatar";
        CardImageColor: {
            /** Format: double */
            dominantA: number;
            /** Format: double */
            dominantB: number;
            /** Format: double */
            dominantL: number;
            game: components["schemas"]["GameType"];
            labColors: Record<string, never>;
            nearestColors: string[];
            /** Format: uuid */
            printTranslationId: string;
            rgbColors: Record<string, never>;
        };
        CardImage: {
            backReference: components["schemas"]["JsonObject"];
            game: components["schemas"]["GameType"];
            /** Format: uuid */
            imageId: string;
            /** Format: uuid */
            printTranslationId: string;
            /** Format: int32 */
            weight: number;
        };
        Image: {
            /** Format: date-time */
            createdAt: string;
            deletedAt?: string | null;
            fileName: string;
            game: components["schemas"]["GameType"];
            /** Format: uuid */
            id: string;
            metadata?: Record<string, never> | null;
            originUrl?: string | null;
            path: string;
            processedAt?: string | null;
            startedProcessingAt?: string | null;
            subject: components["schemas"]["ImageSubject"];
            type: string;
            uploadedAt?: string | null;
        };
        ResolvedPrintImage: {
            cardImage: components["schemas"]["CardImage"];
            image: components["schemas"]["Image"];
        };
        CardImageExtras: {
            artworkLayout?: string | null;
            game: components["schemas"]["GameType"];
            /** Format: uuid */
            printTranslationId: string;
        };
        PrintTranslationSummary: {
            imageColors?: components["schemas"]["CardImageColor"] | null;
            imageEntries: components["schemas"]["ResolvedPrintImage"][];
            imageExtras?: components["schemas"]["CardImageExtras"] | null;
            /** Format: uuid */
            printTranslationId: string;
        };
        "DataApiResponse-PrintTranslationSummary": {
            data: components["schemas"]["PrintTranslationSummary"];
            /** Format: int32 */
            statusCode: number;
        };
        PrintImagesApiUpdateArtworkLayoutRequest: {
            artworkLayout: string;
        };
        PrintImagesApiEvaluateImageResponse: {
            colors?: components["schemas"]["CardImageColor"] | null;
            cropImageData?: string | null;
            thumbnailImageData?: string | null;
        };
        "DataApiResponse-PrintImagesApiEvaluateImageResponse": {
            data: components["schemas"]["PrintImagesApiEvaluateImageResponse"];
            /** Format: int32 */
            statusCode: number;
        };
        "DataApiResponse-ResolvedPrintImage": {
            data: components["schemas"]["ResolvedPrintImage"];
            /** Format: int32 */
            statusCode: number;
        };
        PrintImagesApiUpdateImageWeightRequest: {
            /** Format: int32 */
            weight?: number;
        };
        SetImage: {
            backReference?: components["schemas"]["JsonObject"] | null;
            game: components["schemas"]["GameType"];
            /** Format: uuid */
            imageId: string;
            /** Format: uuid */
            setTranslationId: string;
            /** Format: int32 */
            weight: number;
        };
        ResolvedSetImage: {
            image: components["schemas"]["Image"];
            setImage: components["schemas"]["SetImage"];
        };
        SetTranslationSummary: {
            imageEntries: components["schemas"]["ResolvedSetImage"][];
            /** Format: uuid */
            setTranslationId: string;
        };
        "DataApiResponse-SetTranslationSummary": {
            data: components["schemas"]["SetTranslationSummary"];
            /** Format: int32 */
            statusCode: number;
        };
        "DataApiResponse-ResolvedSetImage": {
            data: components["schemas"]["ResolvedSetImage"];
            /** Format: int32 */
            statusCode: number;
        };
        SetImagesApiUpdateImageWeightRequest: {
            /** Format: int32 */
            weight?: number;
        };
        /** @enum {string} */
        QaStatus: "TO_BE_REVIEWED" | "UNAPPROVED" | "APPROVED";
        QaPrint: {
            /** Format: date-time */
            createdAt: string;
            game: components["schemas"]["GameType"];
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            printTranslationId: string;
            status: components["schemas"]["QaStatus"];
            subjectFieldNotes: components["schemas"]["JsonObject"];
            subjectStatus: components["schemas"]["JsonObject"];
            /** Format: date-time */
            syncedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "DataApiResponse-QaPrint": {
            data: components["schemas"]["QaPrint"];
            /** Format: int32 */
            statusCode: number;
        };
        "SectionPage-QaPrint": {
            entries: components["schemas"]["QaPrint"][];
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            max: number;
            /** Format: int32 */
            offset: number;
        };
        QaApiUpdateEntriesRequest: {
            entryIds: string[];
            newStatus: components["schemas"]["QaStatus"];
        };
        QaApiEntryWithData: {
            allData: {
                [key: string]: Record<string, never>;
            };
            /** Format: uuid */
            printId: string;
            qaPrint: components["schemas"]["QaPrint"];
        };
        "DataApiResponse-QaApiEntryWithData": {
            data: components["schemas"]["QaApiEntryWithData"];
            /** Format: int32 */
            statusCode: number;
        };
        QaSubjectFieldNote: {
            note: string;
            /** Format: int32 */
            severity?: number;
            status: components["schemas"]["QaStatus"];
        };
        QaApiUpdateEntryRequest: {
            status?: components["schemas"]["QaStatus"] | null;
            subjectFieldNotes?: null | {
                [key: string]: components["schemas"]["QaSubjectFieldNote"];
            };
            subjectStatus?: null | {
                [key: string]: "TO_BE_REVIEWED" | "UNAPPROVED" | "APPROVED";
            };
        };
        /** @enum {string} */
        GarnishMethod: "CREATE" | "UPDATE" | "DELETE";
        GarnishRequest: {
            /** Format: date-time */
            createdForAt: string;
            /** Format: uuid */
            createdForState: string;
            deletedAt?: string | null;
            /** Format: uuid */
            id: string;
            lastAppliedAt?: string | null;
            lastAppliedState?: string | null;
            method: components["schemas"]["GarnishMethod"];
            tasks: Record<string, never>;
            tcg: components["schemas"]["GameType"];
        };
        "SimplePage-GarnishRequest": {
            /** Format: int32 */
            currentPage: number;
            hasNextPage: boolean;
            items: components["schemas"]["GarnishRequest"][];
            /** Format: int32 */
            lastPage: number;
            /** Format: int32 */
            nextPage: number;
        };
        ReducedGarnishTask: {
            content: components["schemas"]["JsonObject"];
            type: string;
        };
        CreateGarnishRequest: {
            forState?: string | null;
            method: components["schemas"]["GarnishMethod"];
            /** Format: uuid */
            qaEntryId: string;
            tasks: components["schemas"]["ReducedGarnishTask"][];
            tcg: components["schemas"]["GameType"];
        };
        "DataApiResponse-GarnishRequest": {
            data: components["schemas"]["GarnishRequest"];
            /** Format: int32 */
            statusCode: number;
        };
        /** @enum {string} */
        ImportAnalyticsResultStatus: "SUCCESS" | "WARNING" | "ERROR";
        ImportAnalyticsCounts: {
            /** Format: int32 */
            added: number;
            /** Format: int32 */
            ignored: number;
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            updated: number;
        };
        DataStateAnalysis: {
            /** Format: date-time */
            finishedAt: string;
            results: {
                [key: string]: components["schemas"]["JsonObject"];
            };
            /** Format: date-time */
            startedAt: string;
        };
        ImportAnalyticsResult: {
            status: components["schemas"]["ImportAnalyticsResultStatus"];
            statusMessage?: string | null;
        };
        ImportAnalyticsSourcesDumpling: {
            key: string;
            path: string;
            version: string;
        };
        ImportAnalyticsSources: {
            dumplings: components["schemas"]["ImportAnalyticsSourcesDumpling"][];
            toppings: string[];
        };
        ImportAnalyticsTimings: {
            import: {
                [key: string]: number;
            };
            postImport: {
                [key: string]: number;
            };
            preImport: {
                [key: string]: number;
            };
        };
        ImportAnalytics: {
            environment: string;
            /** Format: date-time */
            finishedAt: string;
            game: components["schemas"]["GameType"];
            importCounts: {
                [key: string]: components["schemas"]["ImportAnalyticsCounts"];
            };
            postAnalysis: components["schemas"]["DataStateAnalysis"];
            preAnalysis: components["schemas"]["DataStateAnalysis"];
            result: components["schemas"]["ImportAnalyticsResult"];
            sources: components["schemas"]["ImportAnalyticsSources"];
            /** Format: date-time */
            startedAt: string;
            subject: string;
            timings: components["schemas"]["ImportAnalyticsTimings"];
        };
        ResolvedImportedState: {
            analytics: components["schemas"]["ImportAnalytics"];
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            importedAt: string;
            tcg: components["schemas"]["GameType"];
        };
        "SimplePage-ResolvedImportedState": {
            /** Format: int32 */
            currentPage: number;
            hasNextPage: boolean;
            items: components["schemas"]["ResolvedImportedState"][];
            /** Format: int32 */
            lastPage: number;
            /** Format: int32 */
            nextPage: number;
        };
        "DataApiResponse-ResolvedImportedState": {
            data: components["schemas"]["ResolvedImportedState"];
            /** Format: int32 */
            statusCode: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
